version: '3'

services:
  python-api-builder:
    build: .
    volumes:
      - ./krak-openapi:/local/input
      - ./krak-python:/local/output
    command: generate -i /local/input/openapi.yml -g python -o /local/output/
